@echo off
echo Cleaning virtual environment...
if exist venv rmdir /s /q venv
echo Creating new clean venv...
python -m venv venv
echo Activating venv...
call venv\Scripts\activate.bat
echo Installing minimal dependencies...
pip install --upgrade pip
pip install -r requirements-ci.txt
echo Done! New venv size should be much smaller.
pause
